import React, { useState } from 'react';
import { FileText, ShieldAlert, Scale, Landmark, ChevronRight, HelpCircle, Sparkles } from 'lucide-react';

export const Terms: React.FC = () => {
  const [activeSection, setActiveSection] = useState<string>('acceptance');

  const sections = [
    {
      id: 'acceptance',
      title: '1. Acceptance of Terms',
      icon: Scale,
      content: 'By accessing or utilizing the Out-of-Home (OOH) media concessions, fractional chief marketing officer advisory services, or digital growth frameworks provided by Ivah Media (hereinafter referred to as the "Company"), you agree to be bound by these Terms and Conditions and all applicable UAE municipal regulations. If you do not agree, you are prohibited from utilizing our strategic assets.'
    },
    {
      id: 'license',
      title: '2. Intellectual Property & License',
      icon: FileText,
      content: 'All campaign mockups, cinematic script layouts, custom translation copy guidelines, and structural design calculations generated by Ivah Media are the exclusive intellectual property of the Company. Clients are granted a non-exclusive, non-transferable, revocable license to utilize approved creatives strictly for the duration of the contracted campaign flight.'
    },
    {
      id: 'negotiations',
      title: '3. Net Media Billing & Rate Policy',
      icon: Landmark,
      content: 'Ivah Media operates under a model of 100% cost transparency. We pass net concession rates from public/private media owners directly to the client, utilizing pre-negotiated volume agreements. All quotes are subject to final municipal permit validation. Double-broker fees or hidden agency commissions are strictly prohibited under our corporate charter.'
    },
    {
      id: 'liabilities',
      title: '4. Limitation of Liability',
      icon: ShieldAlert,
      content: 'Ivah Media acts as a strategic buying facilitator. We are not liable for delayed campaign flights resulting from municipal permit holdovers, severe weather conditions obstructing physical billboard visibility, or digital network outages on programmatic DOOH screens. Attributed conversion lifts are projections and do not constitute legal commercial guarantees.'
    },
    {
      id: 'compliance',
      title: '5. Regional Regulatory Compliance',
      icon: HelpCircle,
      content: 'All outdoor advertising creatives displayed in the UAE must comply with strict bilingual formatting rules (Arabic & English contrast guidelines) and municipal cultural decency acts. Clients assume full responsibility for validating the corporate registration of trademarked logos used in campaign assets.'
    }
  ];

  const handleScrollTo = (id: string) => {
    setActiveSection(id);
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  };

  return (
    <div className="page-terms fade-in">
      {/* SCOPED TERMS STYLES */}
      <style dangerouslySetInnerHTML={{ __html: `
        .page-terms {
          background-color: #080808;
          color: #cbd5e1;
          font-family: 'Montserrat', sans-serif;
          min-height: 100vh;
        }

        .page-terms h1, .page-terms h2, .page-terms h3, .page-terms h4 {
          font-family: 'Outfit', sans-serif;
          font-weight: 700;
          color: #ffffff;
        }

        .page-terms .section-container {
          max-width: 1200px;
          margin: 0 auto;
          padding: 80px 24px;
        }

        /* Hero Banner */
        .page-terms .terms-hero {
          position: relative;
          min-height: 45vh;
          display: flex;
          align-items: center;
          justify-content: center;
          background-image: linear-gradient(to bottom, rgba(8, 8, 8, 0.75) 0%, #080808 100%), url('/bridge_banner.png');
          background-size: cover;
          background-position: center;
          border-bottom: 1px solid rgba(255, 255, 255, 0.05);
        }

        .page-terms .hero-content {
          text-align: center;
          z-index: 10;
          max-width: 800px;
          padding: 0 20px;
        }

        .page-terms .terms-tag {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          font-family: 'Outfit', sans-serif;
          font-size: 0.8rem;
          font-weight: 700;
          color: #f97316;
          letter-spacing: 3px;
          text-transform: uppercase;
          background: rgba(249, 115, 22, 0.08);
          border: 1px solid rgba(249, 115, 22, 0.25);
          padding: 6px 16px;
          border-radius: 30px;
          margin-bottom: 20px;
        }

        /* Sidebar Split Layout */
        .page-terms .terms-layout {
          display: grid;
          grid-template-columns: 0.8fr 1.2fr;
          gap: 60px;
          align-items: flex-start;
          margin-top: 40px;
        }
        @media (max-width: 991px) {
          .page-terms .terms-layout {
            grid-template-columns: 1fr;
            gap: 40px;
          }
        }

        .page-terms .terms-sidebar {
          position: sticky;
          top: 100px;
          display: flex;
          flex-direction: column;
          gap: 12px;
          background: rgba(15, 23, 42, 0.3);
          border: 1px solid rgba(255, 255, 255, 0.04);
          padding: 24px;
          border-radius: 20px;
        }

        .page-terms .sidebar-nav-btn {
          display: flex;
          align-items: center;
          justify-content: space-between;
          background: transparent;
          border: 1px solid transparent;
          padding: 14px 20px;
          border-radius: 10px;
          font-family: 'Outfit', sans-serif;
          font-weight: 600;
          font-size: 0.95rem;
          color: #94a3b8;
          text-align: left;
          cursor: pointer;
          transition: all 0.25s ease;
        }
        .page-terms .sidebar-nav-btn:hover {
          background: rgba(255, 255, 255, 0.02);
          color: #ffffff;
        }
        .page-terms .sidebar-nav-btn.active {
          background: rgba(249, 115, 22, 0.06);
          border-color: rgba(249, 115, 22, 0.2);
          color: #f97316;
        }

        /* Terms Cards */
        .page-terms .terms-content-panel {
          display: flex;
          flex-direction: column;
          gap: 32px;
        }

        .page-terms .terms-card {
          background: rgba(15, 23, 42, 0.2);
          border: 1px solid rgba(255, 255, 255, 0.04);
          border-radius: 20px;
          padding: 40px;
          transition: border-color 0.3s, box-shadow 0.3s;
          scroll-margin-top: 120px;
        }
        .page-terms .terms-card:hover {
          border-color: rgba(249, 115, 22, 0.3);
          box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
        }
        .page-terms .terms-card.active {
          border-color: #f97316;
          box-shadow: 0 10px 30px rgba(249, 115, 22, 0.05);
        }

        .page-terms .terms-card-header {
          display: flex;
          align-items: center;
          gap: 16px;
          margin-bottom: 20px;
        }

        .page-terms .icon-wrapper {
          padding: 10px;
          background: rgba(259, 115, 22, 0.08);
          color: #f97316;
          border-radius: 10px;
        }

        .page-terms .terms-card h3 {
          font-size: 1.4rem;
          margin: 0;
        }
        .page-terms .terms-card p {
          font-size: 1rem;
          line-height: 1.7;
          color: #94a3b8;
          margin: 0;
        }
      ` }} />

      {/* Hero Section */}
      <section className="terms-hero">
        <div className="hero-content">
          <span className="terms-tag">
            <Sparkles size={13} fill="currentColor" /> Regulatory Protocol
          </span>
          <h1 style={{ fontSize: '3.2rem', margin: '0 0 16px 0' }}>Terms of Service</h1>
          <p style={{ color: '#cbd5e1', fontSize: '1.15rem', margin: 0, lineHeight: 1.6 }}>
            Please read the operating terms and net concession directives of Ivah Media before commissioning commercial campaigns.
          </p>
        </div>
      </section>

      {/* Main Content Split */}
      <section className="section-container">
        <div className="terms-layout">
          
          {/* Sticky Left Navigation */}
          <aside className="terms-sidebar">
            <div style={{ fontSize: '0.75rem', fontWeight: 700, color: '#64748b', letterSpacing: '1.5px', textTransform: 'uppercase', marginBottom: '8px', paddingLeft: '8px' }}>
              Document Index
            </div>
            {sections.map((s) => {
              const Icon = s.icon;
              return (
                <button
                  key={s.id}
                  className={`sidebar-nav-btn ${activeSection === s.id ? 'active' : ''}`}
                  onClick={() => handleScrollTo(s.id)}
                >
                  <span style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <Icon size={16} />
                    {s.title.split('. ')[1]}
                  </span>
                  <ChevronRight size={14} style={{ opacity: activeSection === s.id ? 1 : 0.2 }} />
                </button>
              );
            })}
          </aside>

          {/* Details Scroll Panel */}
          <div className="terms-content-panel">
            {sections.map((s) => {
              const Icon = s.icon;
              return (
                <div 
                  key={s.id}
                  id={s.id}
                  className={`terms-card ${activeSection === s.id ? 'active' : ''}`}
                >
                  <div className="terms-card-header">
                    <div className="icon-wrapper">
                      <Icon size={22} />
                    </div>
                    <h3>{s.title}</h3>
                  </div>
                  <p>{s.content}</p>
                </div>
              );
            })}
          </div>

        </div>
      </section>
    </div>
  );
};
